Loudness related thing support
leopard-js/leopard pull request #60
Opened 2020-03-21 17:56 UTC by apple502j

This adds LoudnessHandler, which is mostly copy-paste from scratch-audio. Also, adds `Project.fireGreaterThanTrigger` and `Trigger.getOption`/`Trigger.castOption` as well as `Trigger.executed`. In terms of blocks, it adds `loudness` and `when () > ()` trigger.

2020-07-12 23:46 UTC, PullJosh commented
I see you've updated this so it can be merged! I'm excited to take a close look at this PR soon. :)

2022-07-17 22:46 UTC, adroitwhiz requested changes
I have a few questions about the implementation, particularly the way that "greater than" triggers are implemented.

2022-07-17 22:46 UTC, adroitwhiz commented on src/Loudness.js
> +      rms *= 1.63;
This seems to be missing a lot of explanatory comments from Scratch's implementation.

2022-07-17 22:46 UTC, adroitwhiz commented on src/Project.js
> +    this.fireGreatherThanTrigger(Trigger.TIMER_GREATER_THAN);
Scratch seems to implement "edge-activated hats" (what we call "greater-than triggers" here) a bit differently--every step, it evaluates the predicate of the hat (e.g. "is loudness greater than N? is timer greater than N?") which returns either a true or false value. It fires those hat blocks if the predicate evaluates to true and it evaluated to false on the previous step (the predicate is on a rising edge).

This seems like it'd require less per-trigger logic, and the predicate logic can be encapsulated more cleanly. Would that be worth doing?

2022-07-18 23:52 UTC, adroitwhiz commented on src/Sprite.js
> +    return this._project.loudnessHandler.getLoudness();
It looks like Scratch [only recomputes loudness once per step](https://github.com/LLK/scratch-vm/blob/f405e59d01a8f9c0e3e986fb5276667a8a3c7d40/src/blocks/scratch3_sensing.js#L262-L275).

2022-07-24 14:42 UTC, closed without merging